---
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch${BRANCH_NAME}
  labels:
    app: elasticsearch${BRANCH_NAME}
    branch: cdtn${BRANCH_NAME}
spec:
  selector:
    app: elasticsearch${BRANCH_NAME}
  clusterIP: None
  ports:
  - port: ${ES_PORT}
    name: rest
  - port: ${ES_INTER_NODE}
    name: inter-node
