#

include:
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/templates/docker.stage.yml
  #
  - /k8s/elasticsearch/.deploy-elasticsearch-k8s.yml
  #
  - /.gitlab-ci/stages/prepare.yml
  - /.gitlab-ci/stages/quality.yml
  - /.gitlab-ci/stages/build-and-push.yml
  - /.gitlab-ci/stages/notify.yml
  - /.gitlab-ci/stages/deploy.yml
  #


#

stages:
- "Prepare"
- "Code Quality"
- "Registration"
- "Deploy EL Stack"
- "Notify Finished Deployment"
- "Create Code du Travail Numerique Elasticsearch Index"
- "Deploy Code du Travail Numerique"
- "Send Url"
- "Delete Pods"
