#

include:
  - /.gitlab-ci/variables.yml
  - /.gitlab-ci/templates/docker.stage.yml
  #
  - /.gitlab-ci/stages/prepare.yml
  - /.gitlab-ci/stages/quality.yml

#

stages:
- "Prepare"
- "Code Quality"
- "Build and Push Docker Image"
- "Deploy EL Stack"
- "Create Code du Travail Numerique Elasticsearch Index"
- "Deploy Code du Travail Numerique"
- "Send Url"
- "Delete Pods"
