variables:
  DOCKER_HOST: tcp://localhost:2375
  IMAGE_INFRA_BASE_NAME: "infra/images-docker"
  DOCKER_VERSION: "18.06"
  DOCKER_COMPOSE_VERSION: "1.23.2"
  PYTHON_VERSION: "3.6-alpine"
  PIP_VERSION: "11.10.1"
  ELK_STACK_VERSION: "6.4.2"
  ELASTICSEARCH_PORT: 9200
  ELASTICSEARCH_INTER_NODE_PORT: 9300
  KIBANA_PORT: 5601
  APM_SERVER_PORT: 8200
  API_PORT: 1337
  FRONTEND_PORT: 3000
