---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cdtn-api${BRANCH_NAME}
  labels:
    app: cdtn-api${BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdtn-api${BRANCH_NAME}
  template:
    metadata:
      labels:
        app: cdtn-api${BRANCH_NAME}
    spec:
      containers:
      - image:  registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/api:${IMAGE_TAG}
        name: cdtn-api${BRANCH_NAME}
        ports:
        - containerPort: 1337
        livenessProbe:
          httpGet:
            path: /api/v1/version
            port: 1337
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/v1/version
            port: 1337
          initialDelaySeconds: 3
          periodSeconds: 5
        env:
        - name: API_PORT
          value: "1337"
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch${BRANCH_NAME}:9200
        - name: ELASTICSEARCH_LOG_LEVEL
          value: "${ELASTICSEARCH_LOG_LEVEL}"
        - name: APM_SERVER_ACTIVE
          value: "${APM_SERVER_ACTIVE}"
        - name: APM_SERVER_URL
          value: "${APM_SERVER_URL}"
