---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server${BRANCH_NAME}
  labels:
    app: apm-server${BRANCH_NAME}
    branch: cdtn${BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server${BRANCH_NAME}
  template:
    metadata:
      labels:
        app: apm-server${BRANCH_NAME}
    spec:
      containers:
      - name: apm-server${BRANCH_NAME}
        image: docker.elastic.co/apm/apm-server:${ELK_VERSION}
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
        - name: logging.level
          value: "trace"
        - name: setup.kibana.host
          value: "kibana:${KBN_PORT}"
        - name: output.elasticsearch.hosts
          value: "elasticsearch${BRANCH_NAME}:${ES_PORT}"
        - name: output.elasticsearch.enabled
          value: "true"
        ports:
        - containerPort: ${APM_PORT}
