#

.build_and_push_stage: &build_and_push_stage
  extends: .docker_stage
  stage: "Build and Push Docker Image"
  dependencies: []
  before_script:
    - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  script:
    - docker pull $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA || true
    - docker build $DOCKER_BUILD_ARGS --cache-from $IMAGE_NAME:$CI_COMMIT_BEFORE_SHA -t $IMAGE_NAME:$CI_COMMIT_SHA $CONTEXT
    - docker push $IMAGE_NAME

#

Register elasticsearch image:
  <<: *build_and_push_stage
  variables:
    CONTEXT: docker/elasticsearch
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/elasticsearch

Register api image:
  <<: *build_and_push_stage
  variables:
    CONTEXT: packages/code-du-travail-api
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/api

Register frontend image:
  <<: *build_and_push_stage
  variables:
    CONTEXT: packages/code-du-travail-frontend
    DOCKER_BUILD_ARGS: >-
      --build-arg REGISTRY=$CI_REGISTRY_IMAGE
      --build-arg TAG_BASE_IMAGE=$CI_COMMIT_SHA
    IMAGE_NAME: $CI_REGISTRY_IMAGE/frontend

Register data image:
  <<: *build_and_push_stage
  variables:
    CONTEXT: packages/code-du-travail-data
    DOCKER_BUILD_ARGS: ""
    IMAGE_NAME: $CI_REGISTRY_IMAGE/data
