#

.deploy_stage: &deploy_stage
  extends: .deploy-elasticsearch-dev-k8s
  stage: "Deploy EL Stack"
  except:
    - master
  environment:
    name: dev
  dependencies: []
  services:
    - docker:dind
  variables: &deploy_stage_variables
    ENVIRONMENT: $CI_ENVIRONMENT_NAME
    K8S_SERVER: $K8S_SERVER_DEV
    K8S_CLUSTER_NAME: $K8S_CLUSTER_NAME_DEV
    K8S_NAMESPACE: $K8S_NAMESPACE_DEV
    K8S_USERNAME: $K8S_USERNAME_DEV
    K8S_CONTEXT: $K8S_CONTEXT_DEV
    K8S_TOKEN: $K8S_TOKEN_DEV
    IMAGE_TAG: $CI_COMMIT_SHA

#

Deploy Elasticsearch:
  <<: *deploy_stage
  variables:
    <<: *deploy_stage_variables
    ES_PORT: $ELASTICSEARCH_PORT
    ES_INTER_NODE: $ELASTICSEARCH_INTER_NODE_PORT
    CDTN_REGISTRY: $CI_REGISTRY_IMAGE
