#

.notify_stage: &notify_stage
  image: byrnedo/alpine-curl
  variables:
    DEPLOY_ID_FILE: github_deploy_id
  dependencies: []

#

Notify Start:
  <<: *notify_stage
  stage: "Notify Starting Deployment"
  script:
    - sh -x ./k8s/scripts/get-deploy-id.sh
  artifacts:
    paths:
      - github_deploy_id

Notify Fail:
  <<: *notify_stage
  stage: "Notify Finished Deployment"
  when: on_failure
  dependencies:
    - Notify Start
  script:
    - echo "fail"
    - cat github_deploy_id

Notify Success:
  <<: *notify_stage
  stage: "Notify Finished Deployment"
  when: on_success
  dependencies:
    - Notify Start
  script:
    - echo "Success"
    - cat github_deploy_id
