#

.notify_stage: &notify_stage
  variable:
    DEPLOY_ID_FILE: github_deploy_id
  dependencies: []

#

Notify Github Deployment Start:
  <<: *notify_stage
  stage: "Notify Starting Deployment"
  artifacts:
    paths:
      - github_deploy_id
  script:
    - sh -x k8s/scripts/get-github-deploy-id.sh

Notify Github Deployment Fail:
  <<: *notify_stage
  stage: "Notify Finished Deployment"
  when: on_failure
  dependencies:
    - Notify Github Deployment Start
  script:
    - echo "fail"
    - cat github_deploy_id

Notify Github Deployment Success:
  <<: *notify_stage
  stage: "Notify Finished Deployment"
  when: on_success
  dependencies:
    - Notify Github Deployment Start
  script:
    - echo "Success"
    - cat github_deploy_id
