#

.notify_stage: &notify_stage
  image: python:$PYTHON_VERSION
  variables:
    DEPLOY_ID_FILE: github_deploy_id
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - /var/cache/apk
  before_script:
    - apk update && apk add curl
  dependencies: []

#

Notify Starting Deployment:
  <<: *notify_stage
  stage: "Build and Push Docker Image"
  script:
    - sh ./k8s/scripts/get-deploy-id.sh
  artifacts:
    paths:
      - github_deploy_id

Notify Fail:
  <<: *notify_stage
  stage: "Notify Finished Deployment"
  when: on_failure
  dependencies:
    - Notify Starting Deployment
  script:
    - echo "fail"
    - cat github_deploy_id

Notify Success:
  <<: *notify_stage
  stage: "Notify Finished Deployment"
  when: on_success
  dependencies:
    - Notify Starting Deployment
  script:
    - echo "Success"
    - cat github_deploy_id
