#

.prepare_stage: &prepare_stage
  stage: "Prepare"
  dependencies: []

#

Prepare socialgouv/cdtn base image:
  <<: *prepare_stage
  extends: .docker_stage
  before_script:
  - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
  # NOTE(douglasduteil): do not fail if no previous sha image exist
  - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_BEFORE_SHA || true
  script:
  - echo "Build $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA from $CI_REGISTRY_IMAGE:$CI_COMMIT_BEFORE_SHA"
  - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_BEFORE_SHA -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
  - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

Prepare .env file:
  stage: "Prepare"
  image: node:10-alpine
  script:
  - node scripts/setup-env.js
  artifacts:
    paths:
    - .env
    - codecov.yml
    - docker-compose.yml
