apiVersion: v1
kind: Service
metadata:
  name: kibana${HASH_BRANCH_NAME}
  labels:
    app: kibana${HASH_BRANCH_NAME}
    branch: cdtn${HASH_BRANCH_NAME}
spec:
  ports:
  - port: 5601
  selector:
    app: kibana${HASH_BRANCH_NAME}
