---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cdtn-frontend${BRANCH_NAME}
  labels:
    app: cdtn-frontend${BRANCH_NAME}
    branch: cdtn${BRANCH_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdtn-frontend${BRANCH_NAME}
  template:
    metadata:
      labels:
        app: cdtn-frontend${BRANCH_NAME}
    spec:
      containers:
      - image:  registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/frontend:${IMAGE_TAG}
        name: cdtn-frontend
        ports:
        - containerPort: ${PORT}
        livenessProbe:
          httpGet:
            path: /
            port: ${PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: ${PORT}
          initialDelaySeconds: 3
          periodSeconds: 5
        env:
        - name: API_URL
          value: http://code-du-travail-numerique-api${BRANCH_NAME}.${ENVIRONMENT}.factory.social.gouv.fr/api/v1
