.deploy-code-du-travail-data-k8s:
  image:
    name: $CI_REGISTRY/$IMAGE_INFRA_BASE_NAME/docker-kube:latest
    entrypoint: [""]
  before_script:
  - /apps/create-kubeconfig.sh
  - envsubst < k8s/code-du-travail-data/deployment-code-du-travail-data.yml > k8s/code-du-travail-data/deployment-cdtn-data.yml
  script:
  - k8s/code-du-travail-data/scripts/create-code-du-travail-elasticsearch-index.sh $BRANCH_NAME
  allow_failure: false
