---
apiVersion: v1
kind: Pod
metadata:
  name: cdtn-data${BRANCH_NAME}
  labels:
    app: cdtn-data${BRANCH_NAME}
    branch: cdtn${BRANCH_NAME}
spec:
  containers:
  - name: cdtn-data${BRANCH_NAME}
    image: registry.gitlab.factory.social.gouv.fr/socialgouv/code-du-travail-numerique/data:${IMAGE_TAG}
    env:
    - name: ELASTICSEARCH_URL
      value: http://elasticsearch${BRANCH_NAME}:${ES_PORT}
  restartPolicy: Never
  initContainers:
  - name: wait-for-elasticsearch
    image: alpine
    imagePullPolicy: Always
    command:
    - sh
    - -c
    - |
      apk --no-cache add curl
      while [[ $(curl --silent --output /dev/null --request GET --write-out "%{http_code}" "http://elasticsearch${BRANCH_NAME}:${ES_PORT}") -ne 200 ]]; do
        echo "Not ready"
        sleep 5s
      done
      echo Ready
